name: Emergency Deploy to Production

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Emergency deployment reason"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku Production (Emergency)
        uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: scheduling-of-care
          heroku_email: trongducnbk43@gmail.com
          dontautocreate: true

      - name: Log Emergency Deployment
        run: |
          echo "🚨 Emergency deployment executed!"
          echo "Reason: ${{ github.event.inputs.reason }}"
